version: '3.7'

services:
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/alumni/staticfiles
      - media_volume:/home/app/alumni/mediafiles
    ports:
      - 80:80
    depends_on:
      - alumni

  alumni:
    build:
      context: back
      dockerfile: prod.Dockerfile
    command: gunicorn alumni.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/alumni/staticfiles
      - media_volume:/home/app/alumni/mediafiles
    expose:
      - 8000
    env_file:
      - env/.env.prod
    depends_on:
      - postgres

  postgres:
    image: postgres:12.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - env/.env.db.prod

volumes:
  postgres_data:
  static_volume:
  media_volume: