version: '3.7'

services:
  back:
    build: back/
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./back/app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - env/.env.dev
    restart: unless-stopped
    depends_on:
      - postgres

  postgres:
    image: postgres:12.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - env/.env.db.dev
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    volumes:
    - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    ports:
      - 5050:80
    env_file:
      - env/.env.pgadmin.dev
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin_data: